### NLP, 텍스트 분석

- Natural Language Processing: 기계가 인간의 언어를 이해하고 해석하는 데 중점. 기계번역, 질의응답시스템
- 텍스트 분석: 비정형 텍스트에서 의미있는 정보를 추출하는 것에 중점
- NLP는 텍스트 분석을 향상하게 하는 기반기술
- NLP와 텍스트 분석의 근간에는 머신러닝이 존재. 과거 언어적인 룰 기반 시스템에서 텍스트 데이터 기반으로 모델을 학습하고 예측
- 텍스트 분석은 머신러닝, 언어 이해, 통계 등을 활용한 모델 수립, 정보 추출을 통해 인사이트 및 예측 분석 등의 분석 작업 수행
  - 텍스트 분류: 신문기사 카테고리 분류, 스팸 메일 검출 프로그램, 지도학습
  - 감성 분석: 감정/판단/믿음/의견/기분 등의 주관적 요소 분석. 소셜미디어 감정분석, 영화 리뷰, 여론조사 의견분석, 지도학습, 비지도학습
  - 텍스트 요약: 텍스트 내에서 중요한 주제나 중심 사상을 추출. 토픽 모델링
  - 텍스트 군집화와 유사도 측정: 비슷한 유형의 문서에 대해 군집화 수행. 비지도 학습

Text 분석 수행 프로세스
- 텍스트 정규화
  - 클렌징, 토큰화, 필터링/스톱워드 제거/철자 수정, Stemming, Lemmatization
- 피처 벡터화 변환
  - Bag of Words: Count 기반, TF-IDF 기반
  - Word2Vec
- ML 모델 수립 및 학습/예측/평가

텍스트 전처리 - 텍스트 정규화
- 클렌징: 분석에 방해되는 불필요한 문자, 기호를 사전에 제거. HTML, XML 태그나 특정 기호
- 토큰화: 문서에서 문장을 분리하는 문장 토큰화와, 문장에서 단어를 토큰으로 분리하는 단어 토큰화
- 필터링/스톱워드 제거/철자 수정: 분석에 큰 의미가 없는 단어를 제거
- Stemming, Lemmatization: 문법적 또는 의미적으로 변화하는 단어의 원형을 찾음
  - Stemming은 원형 단어로 변환 시 일반적인 방법을 적용하거나 더 단순화된 방법을 적용(단어만 입력받아서 원형을 탐색함)
  - Lemmatization이 Stemming보다 정교하며 의미론적인 기반에서 단어의 원형을 찾음(단어와 품사를 함께 입력해서 원형을 탐색)

In [ ]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [ ]:
# 문장 토큰화(sent tokenize): 마침표, 개행문자(\n), 정규표현식
from nltk import sent_tokenize

text_sample = 'The Matrix is everywhere its all around us, here even in this room. \
              You can see it out your window or on your television. \
              You feel it when you go to work, or go to church or pay your taxes.'
sentences = sent_tokenize(text=text_sample)
print(sentences)
print(type(sentences), len(sentences))

['The Matrix is everywhere its all around us, here even in this room.', 'You can see it out your window or on your television.', 'You feel it when you go to work, or go to church or pay your taxes.']
<class 'list'> 3


In [ ]:
# 단어 토큰화(word_tokenize): 공백, 콤마, 마침표, 개행문자, 정규표현식
from nltk import word_tokenize

sentence = 'The Matrix is everywhere its all around us, here even in this room.'
words = word_tokenize(sentence)
print(words)
print(type(words), len(words))

['The', 'Matrix', 'is', 'everywhere', 'its', 'all', 'around', 'us', ',', 'here', 'even', 'in', 'this', 'room', '.']
<class 'list'> 15


In [ ]:
# 문서에 대해 모든 단어를 토큰화
from nltk import word_tokenize, sent_tokenize

def tokenize_text(text):
  sentences = sent_tokenize(text) # 문장별 분리토큰
  word_tokens = [word_tokenize(sentence) for sentence in sentences]
  return word_tokens

word_tokens = tokenize_text(text_sample)
print(word_tokens)
print(type(word_tokens),len(word_tokens))


[['The', 'Matrix', 'is', 'everywhere', 'its', 'all', 'around', 'us', ',', 'here', 'even', 'in', 'this', 'room', '.'], ['You', 'can', 'see', 'it', 'out', 'your', 'window', 'or', 'on', 'your', 'television', '.'], ['You', 'feel', 'it', 'when', 'you', 'go', 'to', 'work', ',', 'or', 'go', 'to', 'church', 'or', 'pay', 'your', 'taxes', '.']]
<class 'list'> 3


In [ ]:
# 스톱워드 제거: the, is, a, will와 같이 문맥적으로 큰 의미가 없는 단어를 제거
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
# NLTK english stopwords 갯수 확인
print(len(nltk.corpus.stopwords.words('english')))
print(nltk.corpus.stopwords.words('english')[:20])

179
['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his']


In [ ]:
# stopwords 필터링을 통한 제거
import nltk
stopwords = nltk.corpus.stopwords.words('english')
all_tokens = []
for sentence in word_tokens:
  filtered_words = []
  for word in sentence:
    word = word.lower()
    if word not in stopwords:
      filtered_words.append(word)
  all_tokens.append(filtered_words)
print(all_tokens)

[['matrix', 'everywhere', 'around', 'us', ',', 'even', 'room', '.'], ['see', 'window', 'television', '.'], ['feel', 'go', 'work', ',', 'go', 'church', 'pay', 'taxes', '.']]


In [ ]:
# 문법적 또는 의미적으로 변화하는 단어의 원형을 찾는 방법
# Stemmer(LancasterStemmer)
from nltk.stem import LancasterStemmer
stemmer = LancasterStemmer()
print(stemmer.stem('working'), stemmer.stem('works'), stemmer.stem('worked'))
print(stemmer.stem('amusing'), stemmer.stem('amuses'), stemmer.stem('amused'))
print(stemmer.stem('fancier'), stemmer.stem('fanciest'))

work work work
amus amus amus
fant fanciest


In [ ]:
 import nltk
 nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.


True

In [ ]:
# Lemmatization(WordNetLemmatizer): 정확한 원형 단어 추출을 위해 단어의 품사를 직접 입력
from nltk.stem.wordnet import WordNetLemmatizer

lemma = WordNetLemmatizer()
print(lemma.lemmatize('working','v'), lemma.lemmatize('works','v'), lemma.lemmatize('worked','v'))
print(lemma.lemmatize('amusing','v'), lemma.lemmatize('amuses','v'), lemma.lemmatize('amused','v'))
print(lemma.lemmatize('fancier','a'), lemma.lemmatize('fanciest','a'))

work work work
amuse amuse amuse
fancy fancy


GPU vs CPU

In [6]:
import numpy as np
num_samples = 100
height = 71
width = 71
num_classes = 100

import tensorflow as tf
from keras.applications import Xception
import datetime
start = datetime.datetime.now()



model = Xception(weights = None,
                input_shape = (height, width, 3),
                classes = num_classes)
model.compile(loss='categorical_crossentropy',
              optimizer = 'rmsprop')
x = np.random.random((num_samples, height, width, 3))
y = np.random.random((num_samples, num_classes))
model.fit(x,y,epochs = 3, batch_size = 16)
model.save('my_model.h5')
end = datetime.datetime.now()
time_delta = end - start

Epoch 1/3
7/7 [==============================] - 7s 64ms/step - loss: 234.0989
Epoch 2/3
7/7 [==============================] - 0s 49ms/step - loss: 243.7826
Epoch 3/3
7/7 [==============================] - 0s 49ms/step - loss: 245.0283


In [7]:
print('걸린 시간:{}초'.format(time_delta.seconds))

걸린 시간:9초


In [4]:
import numpy as np
num_samples = 100
height = 71
width = 71
num_classes = 100

import tensorflow as tf
from keras.applications import Xception
import datetime
start = datetime.datetime.now()


with tf.device('/cpu:0'):
  model = Xception(weights = None,
                  input_shape = (height, width, 3),
                  classes = num_classes)
  model.compile(loss='categorical_crossentropy',
                optimizer = 'rmsprop')
  x = np.random.random((num_samples, height, width, 3))
  y = np.random.random((num_samples, num_classes))
  model.fit(x,y,epochs = 3, batch_size = 16)
  model.save('my_model.h5')
end = datetime.datetime.now()
time_delta = end - start

Epoch 1/3
7/7 [==============================] - 17s 1s/step - loss: 231.3479
Epoch 2/3
7/7 [==============================] - 10s 1s/step - loss: 239.0170
Epoch 3/3
7/7 [==============================] - 10s 1s/step - loss: 240.1834


In [5]:
print('걸린 시간:{}초'.format(time_delta.seconds))

걸린 시간:38초


피처 벡터화: One-hot encoding
Bag of Words: 문맥이나 순서를 무시하고 일괄적으로 단어에 대한 빈도값을 부여해 피처값을 추출하는 모델

단점: 문맥 의미 반영 부족, 희소 행렬 문제,

BOW에서 피처 벡터화: 모든 단어를 컬럼 형태로 나열하고 각 문서에서 해달 단어의 횟수나 정규화된 빈도를 값으로 부여하는 데이터 세트 모델로 변경하는 것.

피처 벡터화 방식: 커운트 기반, TF-IDF(Term Frequency - Inverse Documnet Frequency) 기반 벡터화

카운트 벡터화: 카운트값이 높을수록 중요한 단어로 인식. 특성상 자주 사용되는 보편적인 단어까지 높은 값 부여

TF-IDF: 모든 문서에서 전반적으로 자주 나타나는 단어에 대해 패널티 부여. '빈번하게', '당연히', '조직', '업무' 등..

파라미터

- max_df: 너무 높은 빈도수를 가지는 단어 피처를 제외
- min_df: 너무 낮은 빈도수를 가지는 단어 피처를 제외
- max_features: 추출하는 피처의 개수를 제한하며 정수로 값을 지정
- stop_words: 'english'로 지정하면 스톱워드로 지정된 단어는 추출에서 제외. 한글은 목록을 직접 작성해서 넘겨주는 수밖에 없음..
- n_gram_range: 튜플 형태로 (범위 최솟값, 범위 최댓값)을 지정
- analyzer: 피처 추출을 수행하는 단위. 디폴트는 'word'
- token_pattern: 토큰화를 수행하는 정규 표현식 패턴 지정
- tokenizer: 토큰화를 별도의 커스텀 함수로 이용시 적용

In [2]:
# ndarray 객체 생성
import numpy as np
dense = np.array([[3,0,1],[0,2,0]])
dense

array([[3, 0, 1],
       [0, 2, 0]])

In [3]:
# 희소행렬 - COO 형식
from scipy import sparse
data = np.array([3,1,2]) # 0이 아닌 데이터
row_pos = np.array([0,0,1])
col_pos = np.array([0,2,1])
sparse_coo = sparse.coo_matrix((data, (row_pos, col_pos)))
print(sparse_coo)

  (0, 0)	3
  (0, 2)	1
  (1, 1)	2


In [10]:
# 희소행렬 - CSR 형식
dense2 = np.array([[0,0,1,0,0,5],
                  [1,4,0,3,2,5],
                  [0,6,0,3,0,0],
                  [2,0,0,0,0,0],
                  [0,0,0,7,0,8],
                  [1,0,0,0,0,0]])
data2 = np.array([1,5,1,4,3,2,5,6,3,2,7,8,1])
row_pos = np.array([0,0,1,1,1,1,1,2,2,3,4,4,5])
col_pos = np.array([2,5,0,1,3,4,5,1,3,0,3,5,0])

# COO 형식으로 변환
sparse_coo = sparse.coo_matrix((data2,(row_pos, col_pos)))
print(sparse_coo)
print(sparse_coo.toarray())
print()

# CSR 형식으로 변환
# 행 위치 배열의 고유한 값들의 시작 위치 인덱스를 배열로 생성
# 끝에는 전체 개수인 13을 넣어준다.
row_pos_ind = np.array([0,2,7,9,10,12,13])
sparse_csr = sparse.csr_matrix((data2, col_pos, row_pos_ind))
print(sparse_csr)
print(sparse_csr.toarray())

  (0, 2)	1
  (0, 5)	5
  (1, 0)	1
  (1, 1)	4
  (1, 3)	3
  (1, 4)	2
  (1, 5)	5
  (2, 1)	6
  (2, 3)	3
  (3, 0)	2
  (4, 3)	7
  (4, 5)	8
  (5, 0)	1
[[0 0 1 0 0 5]
 [1 4 0 3 2 5]
 [0 6 0 3 0 0]
 [2 0 0 0 0 0]
 [0 0 0 7 0 8]
 [1 0 0 0 0 0]]

  (0, 2)	1
  (0, 5)	5
  (1, 0)	1
  (1, 1)	4
  (1, 3)	3
  (1, 4)	2
  (1, 5)	5
  (2, 1)	6
  (2, 3)	3
  (3, 0)	2
  (4, 3)	7
  (4, 5)	8
  (5, 0)	1
[[0 0 1 0 0 5]
 [1 4 0 3 2 5]
 [0 6 0 3 0 0]
 [2 0 0 0 0 0]
 [0 0 0 7 0 8]
 [1 0 0 0 0 0]]


In [12]:
# DictVectorizer : 문서에서 단어의 사용빈도를 나타내는 딕셔너리 정보를 입력받아
# BOW 인코딩한 수치 벡터로 전환
from sklearn.feature_extraction import DictVectorizer
v = DictVectorizer(sparse = False)
D = [{'A':1,'B':2},{'B':3,'C':1}]
X = v.fit_transform(D)
print(X)
print(v.feature_names_) # 어떤 Feature가 있는지 알려줌
print(v.vocabulary_) # Feature의 순서 알려줌
print(v.transform({'C':4,'D':3})) # fit이 없으면, 기존에 세팅되어있는 Dict에
                            # 반영되기 때문에, C는 추가되지만 D는 추가되지 않음.
                            # -> 말뭉치 사전

[[1. 2. 0.]
 [0. 3. 1.]]
['A', 'B', 'C']
{'A': 0, 'B': 1, 'C': 2}
[[0. 0. 4.]]


In [14]:
# CountVectorizer
from sklearn.feature_extraction.text import CountVectorizer
corpus = [
    'This is the first document.',
    'This is the second document.',
    'And the third one',
    'Is this the first document?',
    'The last document?'
]
vect = CountVectorizer()
vect.fit(corpus)
print(vect.get_feature_names())
print(vect.vocabulary_)


['and', 'document', 'first', 'is', 'last', 'one', 'second', 'the', 'third', 'this']
{'this': 9, 'is': 3, 'the': 7, 'first': 2, 'document': 1, 'second': 6, 'and': 0, 'third': 8, 'one': 5, 'last': 4}


In [16]:
print(vect.transform(['This is the second document.']).toarray())
# 위에 있는 vocabulary의 숫자에 맞춰 배열 인덱스 위치로 반환해 준 것.

[[0 1 0 1 0 0 1 1 0 1]]


In [17]:
print(vect.transform(['Something completely new.']).toarray())
# 위에 있는 vocabulary의 목록에 단어들이 한 개도 포함되어 있지 않음.

[[0 0 0 0 0 0 0 0 0 0]]


In [18]:
print(vect.transform(corpus).toarray())

[[0 1 1 1 0 0 0 1 0 1]
 [0 1 0 1 0 0 1 1 0 1]
 [1 0 0 0 0 1 0 1 1 0]
 [0 1 1 1 0 0 0 1 0 1]
 [0 1 0 0 1 0 0 1 0 0]]


In [19]:
# Stop Words는 문서에서 단어장을 생성할 때 무시할 수 있는 단어.
# 보통 영어의 관사, 접속사, 한국어의 조사 등

vect = CountVectorizer(stop_words=['and','is','the','this']).fit(corpus)
vect.vocabulary_
# Stop Words가 빠지고 나머지 단어들만 남게 된다.

{'first': 1, 'document': 0, 'second': 4, 'third': 5, 'one': 3, 'last': 2}

In [20]:
vect = CountVectorizer(stop_words='english').fit(corpus)
vect.vocabulary_

{'document': 0, 'second': 1}

In [21]:
# analyzer, tokenizer, token_pattern 등의 인수로 사용할 토큰 생성기를 선택
# 문자 단위로 분해
vect = CountVectorizer(analyzer="char").fit(corpus)
vect.vocabulary_

{'t': 16,
 'h': 8,
 'i': 9,
 's': 15,
 ' ': 0,
 'e': 6,
 'f': 7,
 'r': 14,
 'd': 5,
 'o': 13,
 'c': 4,
 'u': 17,
 'm': 11,
 'n': 12,
 '.': 1,
 'a': 3,
 '?': 2,
 'l': 10}

In [22]:
vect = CountVectorizer(token_pattern = 't\w+').fit(corpus)
vect.vocabulary_

{'this': 2, 'the': 0, 'third': 1}

In [24]:
# n-그램은 단어장 생성에 사용할 토큰의 크기 결정
vect = CountVectorizer(ngram_range=(1,2)).fit(corpus)
vect.vocabulary_

{'this': 20,
 'is': 5,
 'the': 13,
 'first': 3,
 'document': 2,
 'this is': 21,
 'is the': 6,
 'the first': 14,
 'first document': 4,
 'second': 11,
 'the second': 16,
 'second document': 12,
 'and': 0,
 'third': 18,
 'one': 10,
 'and the': 1,
 'the third': 17,
 'third one': 19,
 'is this': 7,
 'this the': 22,
 'last': 8,
 'the last': 15,
 'last document': 9}

In [25]:
vect = CountVectorizer(ngram_range=(1,2),token_pattern = 't\w+').fit(corpus)
vect.vocabulary_

{'this': 3, 'the': 0, 'this the': 4, 'third': 2, 'the third': 1}

TF-IDF(Term Frequency - Inverse Document Frequency) 인코딩은 단어를 갯수 그대로 카운트하지 않고, 모든 문서에 공통적으로 들어 있는 단어의 경우 문서 구별 능력이 떨어진다고 보아 가중치를 축소한다.

문서 d(document)와 단어 t에 대해 다음와 같이 계산한다.

tf-idf(d,t) = tf(d,t)*idf(t)

- tf(d,t): term frequency. 특정한 단어의 빈도 수
- idf(t): inverse document frequency. 특정한 단어가 들어 있는 문서의 수에 반비례하는 수
- n: 전체 문서의 수
- df(t): 단어 t를 가진 문서의 수
- idf(d,t) = log(n/(1+df(t)))

In [26]:
corpus = ["""
The Corpus of Contemporary American English (COCA) is the only large, 
genre-balanced corpus of American English. COCA is probably the most 
widely-used corpus of English, and it is related to many other corpora of 
English that we have created, which offer unparalleled insight into variation 
in English.
"""]

In [29]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidv = TfidfVectorizer(stop_words='english').fit(corpus)
print(tfidv.get_feature_names())
print()
print(tfidv.vocabulary_)
print()
print(tfidv.transform(corpus).toarray())
print(tfidv.transform(['This is the second document']).toarray())

['american', 'balanced', 'coca', 'contemporary', 'corpora', 'corpus', 'created', 'english', 'genre', 'insight', 'large', 'offer', 'probably', 'related', 'unparalleled', 'used', 'variation', 'widely']

{'corpus': 5, 'contemporary': 3, 'american': 0, 'english': 7, 'coca': 2, 'large': 10, 'genre': 8, 'balanced': 1, 'probably': 12, 'widely': 17, 'used': 15, 'related': 13, 'corpora': 4, 'created': 6, 'offer': 11, 'unparalleled': 14, 'insight': 9, 'variation': 16}

[[0.26726124 0.13363062 0.26726124 0.13363062 0.13363062 0.40089186
  0.13363062 0.6681531  0.13363062 0.13363062 0.13363062 0.13363062
  0.13363062 0.13363062 0.13363062 0.13363062 0.13363062 0.13363062]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
